# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 15:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='e.g introduce college title', max_length=50, null=True)),
                ('cover_image', models.CharField(blank=True, max_length=1024, null=True, verbose_name='URL of image')),
                ('body', models.CharField(default='', help_text='e.g introduce college body', max_length=50, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='e.g introduce profession title', max_length=50, null=True)),
                ('cover_image', models.CharField(blank=True, max_length=1024, null=True, verbose_name='URL of image')),
                ('body', models.CharField(default='', help_text='e.g introduce profession body', max_length=50, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='e.g introduce school title', max_length=50, null=True)),
                ('cover_image', models.CharField(blank=True, max_length=1024, null=True, verbose_name='URL of image')),
                ('body', models.CharField(default='', help_text='e.g introduce school body', max_length=50, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='e.g introduce teacher title', max_length=50, null=True)),
                ('cover_image', models.CharField(blank=True, max_length=1024, null=True, verbose_name='URL of image')),
                ('body', models.CharField(default='', help_text='e.g introduce teacher body', max_length=50, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
