# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-21 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='created_by',
        ),
    ]
