# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-21 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('introduce', '0002_remove_school_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
