# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-22 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0003_school_created_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School',
            new_name='Introduce',
        ),
        migrations.RemoveField(
            model_name='college',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='profession',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
