# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0004_auto_20180322_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduce',
            name='created_by',
        ),
    ]
