# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0006_introduce_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduce',
            name='created_by',
        ),
    ]
