# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0007_remove_introduce_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroduceBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='e.g introduce title', max_length=50, null=True)),
                ('cover_image', models.CharField(blank=True, max_length=1024, null=True, verbose_name='URL of image')),
                ('description', models.CharField(default='', help_text='e.g introduce description', max_length=50, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='IntroduceCollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='e.g introduce college title', max_length=50, null=True)),
                ('cover_image', models.CharField(blank=True, max_length=1024, null=True, verbose_name='URL of image')),
                ('body', models.CharField(default='', help_text='e.g introduce college body', max_length=50, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='IntroduceProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='e.g introduce profession title', max_length=50, null=True)),
                ('cover_image', models.CharField(blank=True, max_length=1024, null=True, verbose_name='URL of image')),
                ('body', models.CharField(default='', help_text='e.g introduce profession body', max_length=50, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='IntroduceSociety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='e.g introduce society title', max_length=50, null=True)),
                ('cover_image', models.CharField(blank=True, max_length=1024, null=True, verbose_name='URL of image')),
                ('body', models.CharField(default='', help_text='e.g introduce society body', max_length=50, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='IntroduceTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='e.g introduce teacher title', max_length=50, null=True)),
                ('cover_image', models.CharField(blank=True, max_length=1024, null=True, verbose_name='URL of image')),
                ('body', models.CharField(default='', help_text='e.g introduce teacher body', max_length=50, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated')),
            ],
        ),
        migrations.RenameModel(
            old_name='Introduce',
            new_name='IntroduceSchool',
        ),
    ]
