# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0008_auto_20180325_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='introducebase',
            name='introduce_type',
            field=models.CharField(default='', help_text='e.g introduce title', max_length=50, null=True),
        ),
    ]
