# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-17 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clean_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'teacher'), (1, 'student'), (2, 'principal')], default=1, help_text='0:teacher; 1:student; 2:principal'),
        ),
    ]
