# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-29 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180317_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='URL of image'),
        ),
    ]
