# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-29 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.CharField(blank=True, default='https://files.jb51.net/file_images/game/201610/20161015204638166.jpg', max_length=1024, null=True, verbose_name='URL of image'),
        ),
    ]
