# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-01 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, null=True)),
                ('description', models.CharField(default='', max_length=50, null=True)),
                ('cover', models.CharField(blank=True, default='https://files.jb51.net/file_images/game/201610/20161015204638166.jpg', max_length=1024, null=True, verbose_name='URL of cover')),
                ('content', models.TextField(default='', null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
            ],
        ),
    ]
