# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-29 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
