# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-29 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_posts_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comment',
            field=models.IntegerField(default=0, help_text='e.g posts comments_count'),
        ),
    ]
