# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-29 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_posts_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='last_comment',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last_comment'),
            preserve_default=False,
        ),
    ]
