# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-29 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_posts_last_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='last_comment',
            field=models.DateTimeField(default=None, verbose_name='last_comment'),
        ),
    ]
