# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-29 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20180329_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='content',
            field=models.TextField(default='', help_text='e.g comment content'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(default='', help_text='e.g post content'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='last_comment',
            field=models.DateTimeField(auto_now=True, verbose_name='last_comment'),
        ),
    ]
