# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-29 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20180329_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posts',
            name='post_type',
            field=models.IntegerField(default=0, help_text='e.g posts type'),
        ),
    ]
