# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-30 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20180329_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_type',
            field=models.IntegerField(default=1, help_text='e.g posts type'),
        ),
    ]
